version: "3.8" # Specify Docker Compose file version

services:
  web: # Define the FastAPI application service
    build: . # Build the image from the current directory
    ports:
      - "8000:80" # Map port 8000 of the container to port 8000 on the host
    environment:
      - DATABASE_URL=postgresql://postgres:Bright#1270@db:5432/dockert
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Bright#1270
      - POSTGRES_DB=dockert

    depends_on:
      - db # Ensure the database is started first
    volumes:
      - .:/code # Mount the current directory to /app in the container
    networks:
      - mynetwork

  db: # Define the PostgreSQL database service
    image: postgres:16-alpine # Use the official PostgreSQL image

    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Bright#1270
      - POSTGRES_DB=dockert

    expose:
      - 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/ # Persist database data
    networks:
      - mynetwork

volumes:
  postgres_data: # Define a volume for PostgreSQL data

networks:
  mynetwork:
    driver: bridge
