"""initial

Revision ID: 0291eb12264e
Revises: 6be1ae986959
Create Date: 2024-01-25 10:38:05.370763

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0291eb12264e'
down_revision: Union[str, None] = '6be1ae986959'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('subscription', sa.String(), nullable=True))
    op.add_column('users', sa.Column('credits', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'credits')
    op.drop_column('users', 'subscription')
    # ### end Alembic commands ###
