"""Add expiration date

Revision ID: 80d31fcd516b
Revises: 0291eb12264e
Create Date: 2024-01-25 11:30:53.627645

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80d31fcd516b'
down_revision: Union[str, None] = '0291eb12264e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('credits_expiration_date', sa.DateTime(), server_default=sa.text('now() + make_interval(secs=>2592000.0)'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'credits_expiration_date')
    # ### end Alembic commands ###
