"""Delete draft id from files

Revision ID: b9f30a8e4640
Revises: b3309478fdca
Create Date: 2024-02-18 12:01:56.837659

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9f30a8e4640'
down_revision: Union[str, None] = 'b3309478fdca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('files_draft_id_fkey', 'files', type_='foreignkey')
    op.drop_column('files', 'draft_id')
    op.drop_column('files', 'toggle')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('toggle', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('files', sa.Column('draft_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('files_draft_id_fkey', 'files', 'drafts', ['draft_id'], ['id'])
    # ### end Alembic commands ###
